version: 2
updates:
  # Check for outdated client dependencies weekly
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Check for outdated server dependencies weekly
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  # Check for outdated GitHub Actions weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"